// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

public interface FoodPostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rightovers.grpc.FoodPostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string daysLeftToEat = 3;</code>
   * @return The daysLeftToEat.
   */
  java.lang.String getDaysLeftToEat();
  /**
   * <code>string daysLeftToEat = 3;</code>
   * @return The bytes for daysLeftToEat.
   */
  com.google.protobuf.ByteString
      getDaysLeftToEatBytes();

  /**
   * <code>string creatorUserName = 4;</code>
   * @return The creatorUserName.
   */
  java.lang.String getCreatorUserName();
  /**
   * <code>string creatorUserName = 4;</code>
   * @return The bytes for creatorUserName.
   */
  com.google.protobuf.ByteString
      getCreatorUserNameBytes();
}
