// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

/**
 * Protobuf type {@code rightovers.grpc.FoodPostCreatedResponse}
 */
public final class FoodPostCreatedResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rightovers.grpc.FoodPostCreatedResponse)
    FoodPostCreatedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FoodPostCreatedResponse.newBuilder() to construct.
  private FoodPostCreatedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FoodPostCreatedResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FoodPostCreatedResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FoodPostCreatedResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            created_ = input.readBool();
            break;
          }
          case 16: {

            idInDB_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sep3.rightovers.protobuf.Rightovers.internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sep3.rightovers.protobuf.Rightovers.internal_static_rightovers_grpc_FoodPostCreatedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sep3.rightovers.protobuf.FoodPostCreatedResponse.class, sep3.rightovers.protobuf.FoodPostCreatedResponse.Builder.class);
  }

  public static final int CREATED_FIELD_NUMBER = 1;
  private boolean created_;
  /**
   * <code>bool created = 1;</code>
   * @return The created.
   */
  @java.lang.Override
  public boolean getCreated() {
    return created_;
  }

  public static final int IDINDB_FIELD_NUMBER = 2;
  private int idInDB_;
  /**
   * <code>int32 idInDB = 2;</code>
   * @return The idInDB.
   */
  @java.lang.Override
  public int getIdInDB() {
    return idInDB_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (created_ != false) {
      output.writeBool(1, created_);
    }
    if (idInDB_ != 0) {
      output.writeInt32(2, idInDB_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (created_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, created_);
    }
    if (idInDB_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, idInDB_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sep3.rightovers.protobuf.FoodPostCreatedResponse)) {
      return super.equals(obj);
    }
    sep3.rightovers.protobuf.FoodPostCreatedResponse other = (sep3.rightovers.protobuf.FoodPostCreatedResponse) obj;

    if (getCreated()
        != other.getCreated()) return false;
    if (getIdInDB()
        != other.getIdInDB()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCreated());
    hash = (37 * hash) + IDINDB_FIELD_NUMBER;
    hash = (53 * hash) + getIdInDB();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sep3.rightovers.protobuf.FoodPostCreatedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sep3.rightovers.protobuf.FoodPostCreatedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rightovers.grpc.FoodPostCreatedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rightovers.grpc.FoodPostCreatedResponse)
      sep3.rightovers.protobuf.FoodPostCreatedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sep3.rightovers.protobuf.Rightovers.internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sep3.rightovers.protobuf.Rightovers.internal_static_rightovers_grpc_FoodPostCreatedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sep3.rightovers.protobuf.FoodPostCreatedResponse.class, sep3.rightovers.protobuf.FoodPostCreatedResponse.Builder.class);
    }

    // Construct using sep3.rightovers.protobuf.FoodPostCreatedResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      created_ = false;

      idInDB_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sep3.rightovers.protobuf.Rightovers.internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor;
    }

    @java.lang.Override
    public sep3.rightovers.protobuf.FoodPostCreatedResponse getDefaultInstanceForType() {
      return sep3.rightovers.protobuf.FoodPostCreatedResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sep3.rightovers.protobuf.FoodPostCreatedResponse build() {
      sep3.rightovers.protobuf.FoodPostCreatedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sep3.rightovers.protobuf.FoodPostCreatedResponse buildPartial() {
      sep3.rightovers.protobuf.FoodPostCreatedResponse result = new sep3.rightovers.protobuf.FoodPostCreatedResponse(this);
      result.created_ = created_;
      result.idInDB_ = idInDB_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sep3.rightovers.protobuf.FoodPostCreatedResponse) {
        return mergeFrom((sep3.rightovers.protobuf.FoodPostCreatedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sep3.rightovers.protobuf.FoodPostCreatedResponse other) {
      if (other == sep3.rightovers.protobuf.FoodPostCreatedResponse.getDefaultInstance()) return this;
      if (other.getCreated() != false) {
        setCreated(other.getCreated());
      }
      if (other.getIdInDB() != 0) {
        setIdInDB(other.getIdInDB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sep3.rightovers.protobuf.FoodPostCreatedResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sep3.rightovers.protobuf.FoodPostCreatedResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean created_ ;
    /**
     * <code>bool created = 1;</code>
     * @return The created.
     */
    @java.lang.Override
    public boolean getCreated() {
      return created_;
    }
    /**
     * <code>bool created = 1;</code>
     * @param value The created to set.
     * @return This builder for chaining.
     */
    public Builder setCreated(boolean value) {
      
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool created = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreated() {
      
      created_ = false;
      onChanged();
      return this;
    }

    private int idInDB_ ;
    /**
     * <code>int32 idInDB = 2;</code>
     * @return The idInDB.
     */
    @java.lang.Override
    public int getIdInDB() {
      return idInDB_;
    }
    /**
     * <code>int32 idInDB = 2;</code>
     * @param value The idInDB to set.
     * @return This builder for chaining.
     */
    public Builder setIdInDB(int value) {
      
      idInDB_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idInDB = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdInDB() {
      
      idInDB_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rightovers.grpc.FoodPostCreatedResponse)
  }

  // @@protoc_insertion_point(class_scope:rightovers.grpc.FoodPostCreatedResponse)
  private static final sep3.rightovers.protobuf.FoodPostCreatedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sep3.rightovers.protobuf.FoodPostCreatedResponse();
  }

  public static sep3.rightovers.protobuf.FoodPostCreatedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FoodPostCreatedResponse>
      PARSER = new com.google.protobuf.AbstractParser<FoodPostCreatedResponse>() {
    @java.lang.Override
    public FoodPostCreatedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FoodPostCreatedResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FoodPostCreatedResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FoodPostCreatedResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sep3.rightovers.protobuf.FoodPostCreatedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

