// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

public interface FoodPostCreatedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rightovers.grpc.FoodPostCreatedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool created = 1;</code>
   * @return The created.
   */
  boolean getCreated();

  /**
   * <code>int32 idInDB = 2;</code>
   * @return The idInDB.
   */
  int getIdInDB();
}
