// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

public interface GetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rightovers.grpc.GetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string category = 2;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 2;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
