// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

public interface GetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rightovers.grpc.GetAllRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool filler = 1;</code>
   * @return The filler.
   */
  boolean getFiller();
}
