// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rightovers.proto

package sep3.rightovers.protobuf;

public final class Rightovers {
  private Rightovers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rightovers_grpc_FoodPostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rightovers_grpc_FoodPostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rightovers_grpc_FoodPostCreatedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Rightovers.proto\022\017rightovers.grpc\"e\n\017F" +
      "oodPostRequest\022\r\n\005title\030\001 \001(\t\022\023\n\013descrip" +
      "tion\030\002 \001(\t\022\025\n\rdaysLeftToEat\030\003 \001(\t\022\027\n\017cre" +
      "atorUserName\030\004 \001(\t\":\n\027FoodPostCreatedRes" +
      "ponse\022\017\n\007created\030\001 \001(\010\022\016\n\006idInDB\030\002 \001(\0052o" +
      "\n\021RightOversService\022Z\n\014saveFoodPost\022 .ri" +
      "ghtovers.grpc.FoodPostRequest\032(.rightove" +
      "rs.grpc.FoodPostCreatedResponseB\034\n\030sep3." +
      "rightovers.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rightovers_grpc_FoodPostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rightovers_grpc_FoodPostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rightovers_grpc_FoodPostRequest_descriptor,
        new java.lang.String[] { "Title", "Description", "DaysLeftToEat", "CreatorUserName", });
    internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rightovers_grpc_FoodPostCreatedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rightovers_grpc_FoodPostCreatedResponse_descriptor,
        new java.lang.String[] { "Created", "IdInDB", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
